### ISSUE TITLE
Javascript red alert error when I've a timeline on home page at first boot on Firefox

### ISSUE THREAD

**Issue by silvyn** [kixam/TW5-visjsTimeline#20] opened 2015-10-30 08:44 UTC
Hi,

I think it's a timeline vis.js issue, but not sure.

On this example, http://sylvain.naud.in/public/TiddlyWiki/TiddlyWiki-ToDo-Timeline.html, if you put _Timeline_ tiddler to be show when you go home, I've this JavaScript alert error : 

![javascript-error](https://cloud.githubusercontent.com/assets/9981592/10841490/f75a7f16-7ee9-11e5-897f-427e54c33e47.jpg)

I can reproduce this every-time when I just open Firefox and my TW file. I don't have this issue If I have no timeline to show when you open TW.
1. Open Firefox
2. Open TiddlyWiki-ToDo-Timeline.html whith no timeline : No error
3. Put Timeline tiddler in this example to be show in home, save
4. Close Firefox
5. Open Firefox
6. Open TiddlyWiki-ToDo-Timeline.html : you've got this red alert error

Sylvain

**Comment by kixam** [comment] 2015-10-30 09:29
hi @silvyn ,

I already bumped into this bug when e.g. I open this plugin's demo page, but I cannot reproduce it as regularly as you seem to be able to. Until I do, I cannot be certain I got rid of it entirely. Can you please investigate more:
- please provide your version of Firefox, maybe also your plugins and OS
- please try on Chrome or other browsers

I could not reproduce the bug on Firefox 41.0.2 nor on Chrome 46.0.2490.80 on x64 Linux using the demo page at http://kixam.github.io/TW5-visjsTimeline/ and following your steps.

In the meantime, it seems that closing the popup and continue working as if nothing happened, does not have any consequences whatsoever. I suspect the bug is in a (too) early information notice.

**Comment by silvyn** [comment] 2015-10-30 13:16
Hello @kixam 

I had this issue both on Windows 7 (Firefox 41.0.2) and Gnu/Linux (under Fedora 21).
_(I don't use Chrome with lake of backup TW file, don't try yet plugin discuss on GoogleGroups)_.

I confirm your last comment, about closing popup (3 times) and nothing else happened.

I don't reproduce with your demo page, even if a save a local copy and open it. Now I don't reproduce with my own file.. so it's embarrassing for me ;)

**Comment by felixhayashi** [comment] 2015-12-05 17:08
Salut @silvyn @kixam 

This fella troubled me as well:

https://github.com/felixhayashi/TW5-TiddlyMap/issues/163

I also created an issue at visjs repo back then:
https://github.com/almende/vis/issues/1088

At one point, I didn't care anymore what is causing this and just killed the error brute force as it did not seem to cause any damage. @kixam, if you want to prevent this, just copy paste the code below into your widget.

``` javascript
/*** TO AVOID STRANGE LIB ERRORS FROM BUBBLING UP *****************/

if($tw.boot.tasks.trapErrors) {

  var defaultHandler = window.onerror;
  window.onerror = function(errorMsg, url, lineNumber) {
    if(errorMsg.indexOf("NS_ERROR_NOT_AVAILABLE") !== -1
       && url == "$:/plugins/felixhayashi/vis/vis.js") {
      console.error("Strange firefox related vis.js error (see #125)",
                    arguments);
    } else if(errorMsg.indexOf("Permission denied to access property") !== -1) {
      console.error("Strange firefox related vis.js error (see #163)",
                    arguments);
    } else if(defaultHandler) {
      defaultHandler.apply(this, arguments);
    }
  }

}
```

-Felix

**Comment by kixam** [comment] 2015-12-05 17:26
Hallo @felixhayashi ,

Thank you ! That should do it I guess.

However, if it is somehow related to vis.js library or the vis.js plugin, maybe it would be more appropriate and less redundant to put the code in the vis.js plugin and not in derived plugins like TiddlyMap or Timeline ?

**Comment by felixhayashi** [comment] 2015-12-15 13:31
Hi @kixam 

Sorry for the late response.

> However, if it is somehow related to vis.js library or the vis.js plugin, maybe it would be more appropriate and less redundant to put the code in the vis.js plugin and not in derived plugins like TiddlyMap or Timeline?

I hadn't done this so far because I was not sure whether it is my code that is causing this or the visjs/firefox. What you propose makes sense because it is rather unlikely that both our code produce this error independent from vis.js. So I'll add it once I find the time and ping back once it's done so you can remove the code from your plugin.

-Felix

**Comment by kixam** [comment] 2015-12-15 13:58
hi @felixhayashi ,

if I have some time before you do, I will propose a merge for your Vis.js plugin :)

**Closed as completed** 2016-01-05 10:23 UTC
Labels: bug
